# -*- coding: utf-8 -*-
"""AluraStoreBr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtfhOCjQ72FGhffwy_o28yDEKsRDRcz3

### Importação dos dados
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_1.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_4.csv"

loja1 = pd.read_csv(url)
loja2 = pd.read_csv(url2)
loja3 = pd.read_csv(url3)
loja4 = pd.read_csv(url4)

loja1.head()

# Resumo das bases de deados
loja1.info()
loja2.info()
loja3.info()
loja4.info()

# Anlise de valores ausentes
loja1.isnull().sum()
loja2.isnull().sum()
loja3.isnull().sum()
loja4.isnull().sum()

"""#1. Análise do faturamento

"""

# Analise do faturamento de cada loja
lojas = [loja1, loja2, loja3, loja4]
nomes_lojas = ["Loja 1", "Loja 2", "Loja 3", "Loja 4"]
faturamento_total = []
faturamento_rede = 0

for i, loja in enumerate(lojas, start=1):
    # faturamento = loja['Preço'] + loja['Frete']
    faturamento_loja = loja['Preço'].sum()
    faturamento_total.append(faturamento_loja)
    faturamento_rede += faturamento_loja
    print(f"Faturamento da loja {i}: R$ {faturamento_loja:.2f}")

print(f"\nFaturamento Total da rede R$ {faturamento_rede:.2f}")

# Gráfico de barras
plt.bar(nomes_lojas, faturamento_total, color='seagreen', edgecolor='black')
plt.xlabel('Lojas')
plt.ylabel('Faturamento (R$)')
plt.title('Faturamento por Loja')
plt.grid(True, linestyle='--', alpha=0.5)

for i, valor in enumerate(faturamento_total):
    plt.text(i, valor, f'R$ {valor:.2f}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

"""# 2. Vendas por Categoria

"""

# Calculo de vendas por categoria
for i, loja in enumerate(lojas, start=1):
    print(f"\nVendas por categoria - Loja {i}:")
    vendas_categoria = loja.groupby('Categoria do Produto')['Preço'].sum()
    print(vendas_categoria)

categorias = vendas_categoria.index
valores = vendas_categoria.values

plt.figure(figsize=(8, 8))
plt.pie(
    valores,
    labels=categorias,
    autopct='%1.1f%%',
    startangle=90,
    colors=plt.cm.Paired.colors,
    wedgeprops={'edgecolor': 'black'}
)

plt.title("Faturamento por Categoria de Produto (Todas as Lojas)")
plt.axis('equal')
plt.tight_layout()
plt.show()

"""# 3. Média de Avaliação das Lojas"""

avaliacoes = []
for i, loja in enumerate(lojas, start=1):
    media_avaliacoes = loja['Avaliação da compra'].mean()
    avaliacoes.append(media_avaliacoes)
    print(f"Média de avaliações - Loja {i}: {media_avaliacoes:.2f}")

plt.barh(nomes_lojas, avaliacoes, color='seagreen', edgecolor='black')
plt.xlabel('Avaliações')
plt.ylabel('Lojas (R$)')
plt.title('Média de Avaliação das Lojas')
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

"""# 4. Produtos Mais e Menos Vendidos"""

for i, loja in enumerate(lojas, start=1):
    produtos_vendidos = loja['Produto'].value_counts()
    # Ordenar do mais vendido para o menos vendido
    produtos_vendidos = produtos_vendidos.sort_values(ascending=False)
print(f'Produtos mais vendidos {produtos_vendidos.head()}')

print(f'\nProdutos menos vendidos\n:  {produtos_vendidos.tail()}')

"""# 5. Frete Médio por Loja

"""

fretes_medios = []

for i, loja in enumerate(lojas, start=1):
    frete_medio = loja['Frete'].mean()
    print(f"Frete médio da Loja {i}: R$ {frete_medio:.2f}")

"""# 6. Resultado

### Com base na analise efetuado, podemos concluir que:
- Loja que apresentou faturamento mais baixo: **Loja 4**
- Pior avaliação: **Loja 1** (3.98), mas só por uma diferença mínima.
- Frete mais barato: **Loja 4** — ponto positivo nesse quesito.

### Possível decisão:
- Levando em consideração apenas os valores quantitativos a **Loja 4** apresenta o  pior desempenho, com o menor faturamento e a segunda pior avaliação.

- Logo, a **Loja 4** seria a candidata mais lógica para encerramento de suas atividades.

"""